# Generated by Django 2.1.8 on 2019-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editgoapp', '0003_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
