# Generated by Django 2.1.8 on 2019-07-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editgoapp', '0009_creatorcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorcomment',
            name='cblog',
        ),
        migrations.DeleteModel(
            name='CreatorComment',
        ),
    ]
