# Generated by Django 2.1.8 on 2019-07-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editgoapp', '0011_creatorcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorcomment',
            name='cblog',
        ),
        migrations.AddField(
            model_name='creatorcomment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='editgoapp.Creator'),
        ),
    ]
