# Generated by Django 2.1.8 on 2019-07-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editgoapp', '0014_auto_20190719_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500)),
                ('comment_re', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='editgoapp.Comment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
