# Generated by Django 2.1.8 on 2019-07-19 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editgoapp', '0015_commentreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='comment_re',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='editgoapp.Comment'),
        ),
    ]
