# Generated by Django 2.1.8 on 2019-07-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editgoapp', '0016_auto_20190720_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='reply',
            new_name='contents',
        ),
    ]
