# Generated by Django 2.1.8 on 2019-07-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editgoapp', '0018_creatorcommentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcommentreply',
            name='ccomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creplys', to='editgoapp.CreatorComment'),
        ),
    ]
